version: "3"
services:
  react:
    build: ./react
    ports:
      - "3001:3000"

  nodejs:
    build: ./nodejs
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27018/mydb
      MONGODB_URL: mongodb://mongodb:27018/mydb
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"

volumes:
  mongodb_data:
