version: "3"
services:
  react:
    build: ./react
    ports:
      - "3001:3000"
    volumes:
      # - ./react:/usr/src/app # Mount the local react folder
      - ./react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file system polling for changes

  nodejs:
    build: ./nodejs
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    #  mongodb:
    #    condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydb
      MONGODB_URL: mongodb://mongodb:27017/mydb
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
      # Other environment variables...
    volumes:
      - ./nodejs:/usr/src/app # Mount the local nodejs folder

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
